version: "3"

services:
  node:
    build: .
    user: node
    container_name: convertion_api
    tty: true
    stdin_open: true
    command: dev
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 3001:3001
    environment:
      PORT: 3001
    env_file:
      - .env